/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Input from '../packages/input/index.js';
import AjaxLoading from '../packages/ajax-loading/index.js';
import MessageBox from '../packages/message-box/index.js';
import Pagination from '../packages/pagination/index.js';
import CollapseTransition from 'kzjr_ui/src/transitions/collapse-transition';

const components = [
  Button,
  Input,
  AjaxLoading,
  Pagination,
  CollapseTransition
];

const install = function(Vue, opts = {}) {

  components.map(component => {
    Vue.component(component.name, component);
  });

  Vue.use(Loading.directive);

  const ELEMENT = {};
  ELEMENT.size = opts.size || '';

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;

  Vue.prototype.$ELEMENT = ELEMENT;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

module.exports = {
  version: '0.0.5',
  install,
  CollapseTransition,
  Loading,
  Button,
  Input,
  AjaxLoading,
  MessageBox,
  Pagination
};

module.exports.default = module.exports;
